### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by lyrixx** [joemiller/jenkins-statsd-plugin#6]
Can you do a release, with the hpi inside ?

Thanks

**Comment by jstarcher** [comment]
+1

**Comment by vfloyd1121** [comment]
Anyone successful in getting the .hpi file?

**Comment by lyrixx** [comment]
IIRC, we built the hpi without problem. But an official release is often better

**Comment by vfloyd1121** [comment]
Yes, I am looking for an official release.

**Comment by lyrixx** [comment]
ping @joemiller

**Comment by taizilongxu** [comment]
+1

**Comment by lyrixx** [comment]
I guess I will never happen. I'm closing this issue.
